#!/usr/bin/ruby

puts '// Generated by https://github.com/irori/8cc.unl/blob/master/unlcore.scm'
puts
print 'static char unl_core[] ='

while s = ARGF.read(78)
  puts
  print '"' + s + '"'
end
puts ';'
